import { Accommodation } from "@/types/accommodation";

export const API_CONFIG = {
  baseUrl: process.env.NEXT_PUBLIC_API_URL,
  path: {
    users: "/users",
    uploads: "/uploads/images/public",
  },
};

export const dummyAccommodations: Accommodation[] = [
  {
    "id": "acc-001",
    "name": "Green Valley PG",
    "type": "PG",
    "address": "123 MG Road, Bangalore, Karnataka 560001",
    "price": 12000,
    "rating": 4.2,
    "description": "A comfortable paying guest accommodation with all basic amenities included. Perfect for students and working professionals.",
    "verified": true,
    "amenities": ["WiFi", "Meals", "Laundry", "Security", "Power Backup"],
    "email": "contact@greenvalleypg.com",
    "phone": "+91-9876543210",
    "is_active": true,
    "is_deleted": false,
    "created_at": "2024-01-15T10:30:00Z",
    "updated_at": "2024-03-20T14:25:00Z",
    "deleted_at": "",
    "property_type": "both",
    "property_name": "Green Valley Premium PG",
    "images": [
      "https://example.com/images/pg1-1.jpg",
      "https://example.com/images/pg1-2.jpg",
      "https://example.com/images/pg1-3.jpg"
    ],
    "slug": "green-valley-pg-bangalore"
  },
  {
    "id": "acc-002",
    "name": "Metro Apartments",
    "type": "Rental",
    "address": "45 Koramangala, Bangalore, Karnataka 560034",
    "price": 25000,
    "rating": 4.5,
    "description": "Fully furnished 2BHK apartment in prime location with modern amenities and 24/7 security.",
    "verified": true,
    "amenities": ["WiFi", "Parking", "Security", "Gym", "Swimming Pool", "Power Backup"],
    "email": "info@metroapartments.com",
    "phone": "+91-9876543211",
    "is_active": true,
    "is_deleted": false,
    "created_at": "2024-02-10T09:15:00Z",
    "updated_at": "2024-03-25T11:40:00Z",
    "deleted_at": "",
    "property_type": "both",
    "property_name": "Metro Residency",
    "images": [
      "https://example.com/images/rental1-1.jpg",
      "https://example.com/images/rental1-2.jpg"
    ],
    "slug": "metro-apartments-koramangala"
  },
  {
    "id": "acc-003",
    "name": "Student Hub Hostel",
    "type": "Hostel",
    "address": "78 Electronic City, Bangalore, Karnataka 560100",
    "price": 8000,
    "rating": 3.8,
    "description": "Budget-friendly hostel accommodation specifically for students near educational institutions.",
    "verified": false,
    "amenities": ["WiFi", "Meals", "Laundry", "Study Room", "Security"],
    "email": "hostel.studenthub@email.com",
    "phone": "+91-9876543212",
    "is_active": true,
    "is_deleted": false,
    "created_at": "2024-01-05T08:00:00Z",
    "updated_at": "2024-03-18T16:20:00Z",
    "deleted_at": "",
    "property_type": "boys",
    "slug": "student-hub-hostel-electronic-city"
  },
  {
    "id": "acc-004",
    "name": "Urban Stay Co-living",
    "type": "Co-living",
    "address": "22 Indiranagar, Bangalore, Karnataka 560038",
    "price": 15000,
    "rating": 4.7,
    "description": "Premium co-living space with community events, modern facilities, and professional environment.",
    "verified": true,
    "amenities": ["WiFi", "Meals", "Housekeeping", "Gym", "Community Events", "Game Room", "Security"],
    "email": "hello@urbanstay.com",
    "phone": "+91-9876543213",
    "is_active": true,
    "is_deleted": false,
    "created_at": "2024-03-01T12:00:00Z",
    "updated_at": "2024-03-28T09:15:00Z",
    "deleted_at": "",
    "property_type": "both",
    "property_name": "Urban Stay Premium",
    "images": [
      "https://example.com/images/coliving1-1.jpg",
      "https://example.com/images/coliving1-2.jpg",
      "https://example.com/images/coliving1-3.jpg",
      "https://example.com/images/coliving1-4.jpg"
    ],
    "slug": "urban-stay-co-living-indiranagar"
  },
  {
    "id": "acc-005",
    "name": "Rose Girls PG",
    "type": "PG",
    "address": "15 Jayanagar, Bangalore, Karnataka 560041",
    "price": 11000,
    "rating": 4.3,
    "description": "Safe and secure girls PG with homely environment and nutritious food.",
    "verified": true,
    "amenities": ["WiFi", "Meals", "Laundry", "Security", "Power Backup", "CCTV"],
    "email": "rosegirlspg@email.com",
    "phone": "+91-9876543214",
    "is_active": true,
    "is_deleted": false,
    "created_at": "2024-02-20T14:45:00Z",
    "updated_at": "2024-03-22T10:30:00Z",
    "deleted_at": "",
    "property_type": "girls",
    "slug": "rose-girls-pg-jayanagar"
  },
  {
    "id": "acc-006",
    "name": "Tech Park Rental",
    "type": "Rental",
    "address": "33 Whitefield, Bangalore, Karnataka 560066",
    "price": 30000,
    "rating": 4.1,
    "description": "Spacious 3BHK apartment near IT parks with modern amenities and quick access to metro.",
    "verified": true,
    "amenities": ["WiFi", "Parking", "Security", "Power Backup", "Modular Kitchen", "Balcony"],
    "email": "techpark.rentals@email.com",
    "phone": "+91-9876543215",
    "is_active": false,
    "is_deleted": false,
    "created_at": "2024-01-30T11:20:00Z",
    "updated_at": "2024-03-10T13:45:00Z",
    "deleted_at": "",
    "property_type": "both",
    "slug": "tech-park-rental-whitefield"
  }
]
